### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Augustine-edeh** [adetoye-dev/books-library-app#16]
There might be a slight typo in this project's README.md file. Kindly see attached photo for your reference:

![IMG-20230407-WA0002](https://user-images.githubusercontent.com/58579127/230601455-4513e9dd-0e9a-483a-a102-3c6ba90f7fb3.jpg)

**Comment by adetoye-dev** [comment]
Thank you so much Augustine for pointing that out. Will get it fixed ASAP. 👍

**Comment by adetoye-dev** [comment]
This issue has now been fixed
